// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @param {string} pathname
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetThumbHash(pathname) {
    let $resultPromise = /** @type {any} */($Call.ByID(4218870357, pathname));
    return $resultPromise;
}
